# Generated by Django 5.2.1 on 2025-06-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Введите имя автора",
                        max_length=150,
                        verbose_name="First name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Введите фамилию автора",
                        max_length=150,
                        verbose_name="Last name",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Введите дату рождения (YYYY-MM-DD)",
                        null=True,
                        verbose_name="Date of birth",
                    ),
                ),
                (
                    "date_of_death",
                    models.DateField(
                        blank=True,
                        help_text="Введите дату смерти (YYYY-MM-DD)",
                        null=True,
                        verbose_name="Date of death",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение автора",
                        null=True,
                        upload_to="author/image",
                        verbose_name="Image",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Укажите страну проживания автора",
                        max_length=30,
                        null=True,
                        verbose_name="Country",
                    ),
                ),
                (
                    "biography",
                    models.TextField(
                        blank=True,
                        help_text="Укажите биографию автора",
                        null=True,
                        verbose_name="Biography",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
            },
        ),
    ]
