# Generated by Django 5.2.1 on 2025-06-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["author"],
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
    ]
