# Generated by Django 5.2.1 on 2025-06-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_takebook_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='takebook',
            options={'ordering': ['book'], 'verbose_name': 'Аренда книги', 'verbose_name_plural': 'Аренды книг'},
        ),
    ]
