# Generated by Django 5.2.1 on 2025-06-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_takebook_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="takebook",
            options={
                "ordering": ["pk"],
                "verbose_name": "Аренда книги",
                "verbose_name_plural": "Аренды книг",
            },
        ),
    ]
